controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
vich_uploader_images:
    path: /uploads/image/{fileName}
    controller: VichUploaderBundle\Controller\DownloadController::downloadAction
    requirements:
        fileName: .+
    methods: GET